#!/bin/bash

for param in "$@"
do
    # echo "$param"
    name=${param%.*}
    img=`base64 $param | tr -d '\n'`

cat <<EOF > ${name}.json
{
	"filename" : "$param",
	"image": "$img"
}
EOF
  echo ${name}.json
done

# count=1
#
# for param in "$@"
# do
#     echo "$param"
#     dir=${param%.*}
#     mkdir $dir
#     for (( i=1; i<=$count; i++ )); do
#     	#printf '{"filename": "%s", "image": "%s"}\n' "$i-$param" `base64 $param` > $dir/$i-${param}.json
# 	img=`base64 $param | tr -d '\n'`
#
# cat <<EOF > $dir/$i-${param}.json
# {
# 	"filename" : "$i-$param",
# 	"image": "$img"
# }
# EOF
#     done
# done
